service: campo-harmonico

provider:
  name: aws
  runtime: ruby2.5
  region: us-east-1

package:
  exclude:
    - .git
    - .gitignore

functions:
  HarmonicField:
    handler: harmonic_field.process

    events:
      - http:
          path: harmonic_fields
          method: post

resources:
  Resources:
    HarmonicFields:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: harmonic_fields
        AttributeDefinitions:
          - AttributeName: chord
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: chord
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
