service: campo-harmonico

provider:
  name: aws
  runtime: ruby2.5
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: arn:aws:dynamodb:*:*:table/${self:custom.harmonicFieldsTableName}
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:*:*:table/${self:custom.chordsBySessionTableName}

package:
  exclude:
    - .git
    - .gitignore

functions:
  HarmonicField:
    handler: handler.process

    events:
      - http:
          path: harmonic_fields
          method: post

resources:
  Resources:
    HarmonicFields:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.harmonicFieldsTableName}
        AttributeDefinitions:
          - AttributeName: chord
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: chord
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ChordsBySession:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.chordsBySessionTableName}
        AttributeDefinitions:
          - AttributeName: session
            AttributeType: S
        KeySchema:
          - AttributeName: session
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  harmonicFieldsTableName: harmonic_fields
  chordsBySessionTableName: chords_by_session
  dynamodb:
    start:
      migrate: true
